### ISSUE TITLE
Interesting Meteor Collection Hooks discussion...?

### ISSUE THREAD

**Issue by Siyfion** [matb33/meteor-collection-hooks#101]
Rather than a bug per-se, I thought I'd just draw your attention to the discussion going on here: https://forums.meteor.com/t/meteor-collection-hooks-confused/748

**Comment by zimme** [comment]
This is related to #65

**Comment by matb33** [comment]
For the time being, the hooks aren't doing anything beyond firing before and after the intended methods. They are quite dumb, but in that sense they are predictable. However I understand how that might not mesh with some expectations with regards to latency compensation. Will need to think on that, or hopefully hooks will be integrated into core and this type of stuff will be taken care of for us!
