### ISSUE TITLE
insert in .after.insert runs twice

### ISSUE THREAD

**Issue by buduguru** [matb33/meteor-collection-hooks#104]
If we call Collection.insert(smth) in .after.insert then that smth is inserted twice.
This strange behavior happens only if .after.insert is accessible from both client and server.

**Comment by wursttheke** [comment]
We experienced the same thing. There was [a little discussion](https://forums.meteor.com/t/meteor-collection-hooks-confused/748/8) on the forum: 

It seems that the hooks are not run inside the method call, which meteor uses internally when you do a raw insert on the client. To circumvent the problem, we wrap our insert call inside a meteor method. 

So, ideally the hooks should be part of the 'native' meteor insert, update, etc. calls. But I guess this can only be done by altering the core. So I'm referencing this [highly requested feature](https://github.com/meteor/meteor/issues/395) again. :wink:

**Comment by buduguru** [comment]
I ended up putting the code in /server ,  because I do not care for latency compensation in my specific case.

**Comment by matb33** [comment]
The hooks aren't particularly smart -- they just run before/after your call to Collection.insert. If you execute Collection.insert on the client and the server, the hooks will get called twice.

**Comment by renegade7** [comment]
I had the same problem, try to run if(Meteor.isServer) Before your insert
