### ISSUE TITLE
Do collection hooks work on the server

### ISSUE THREAD

**Issue by MurWade** [matb33/meteor-collection-hooks#109]
If you insert on the server, are the hooks meant to run? becuase mine doesnt 

    if(Meteor.isServer)
        Posts.insert({name: 'test'}); // does this cause the hooks to run?

**Comment by dstollie** [comment]
Same for me..

**Comment by matb33** [comment]
They do -- if you can paste more of your code we can help you track down what to change

**Comment by dstollie** [comment]
I was being stupid by creating two insert hooks: one which incremented a counter and one which decremented it. This caused to counter unchanged. No probs which the package for me!

**Comment by zimme** [comment]
@MurWade, Maybe you've defined the hook in client code and run the insert in server code, then the hook won't run.

**Comment by MurWade** [comment]
I have defined my hooks in common code. so client and server. I am using simple schema to combine maybe that is an issue. I will link a repo so you can reproduce it. The code runs twice when i insert from client which is expected but as soon as i insert from server no hooks run.

**Comment by florasolutions** [comment]
I also use simple schema in combination with collection hooks. The hooks are not called.

Collection-hooks are set up in my common code. I only use collection.insert in the server code.

**Comment by florasolutions** [comment]
To confirm: if I do not attach a simple schema to a collection, the hooks are called properly.

I.e. setting up multiple before.insert or before.update hooks and they are all called in the order I have attached them.

What I can see is that SimpleSchema performs its magic before collection hooks. For example, I have an insertDateTime timestamp field in the schema definition. It has denyUpdate : true set in the schema. Upon updating a collection to which this schema is attached, and having the insertDateTime in the data, SimpleSchema says the data does not validate which is correct. The collection hooks never get called in this case.

What I would like is to have the collection hooks fire before SimpleSchema. Is that possible?

**Comment by zimme** [comment]
If validation fails then there is no insert/update and if there isn't an insert/update the before.insert/update hooks won't run. Which I feel is correct.

**Comment by wursttheke** [comment]
@florasolutions you could manually validate against the schema inside a collection hook. That way you can control when which hook is fired.

**Comment by florasolutions** [comment]
@wursttheke I also validate in a method before calling insert/update. The result of the validation is positive at that point, as simple schema does not know whether its an insert or update, but when calling insert/update collection2/simple schema again validates, but now it knows if it's an insert or update. I can never validate in a hook in the above case.

@zimme that is true. Maybe a better hook for me would be before.insert.validation and before.update.validation to have it more semantically correct. I just have some generic processing to do before inserting/updating on common fields available in all my collections and I thought hooks were the best place to do this in order to reduce repeated code.

**Comment by zimme** [comment]
It still is, but it shouldn't do the processing if there isn't an insert because of failed validation, right?

So if the validation passes then the insert/update goes through and your hook with the processing is run.

**Comment by matb33** [comment]
Out of curiosity, could the validation not be done within allow/deny?

**Comment by darkship** [comment]
Hello,

@matb33 There is definitely something with the hooks.
In this repo https://github.com/darkship/test_hooks_with_update_fail, I do an update in the <code>before.update</code> hook but then <code>after.update</code> is never called.

**Comment by matb33** [comment]
@darkship thanks for the repo. I took quick look. Did you mean to forbid access for the client to the `item2` collection? The hook behavior looks completely fine -- you may have simply made a mistake with regards to when the hooks will run (you defined them on both server and client, so you have to pay extra special attention to how things will go down).

**Comment by darkship** [comment]
I was too quick in my explanation. Sorry. 

I didn't care of client side but I updated my repo to allow inserts and updates on <code>item2</code>.
So when I run it, there is no <code>function after update</code> in my shell neither in my client's console.

**Comment by matb33** [comment]
@darkship thanks for this. You helped me uncover a typo that was certainly at the root of many strange side-effects. I'm releasing an update in a few minutes.

**Comment by darkship** [comment]
@matb33 it works, thanks.
