### ISSUE TITLE
Do collection hooks work when inserting into the database directly?

### ISSUE THREAD

**Issue by francisbyrne** [matb33/meteor-collection-hooks#112]
I've written a hook like so:

```
Recordings.after.insert(function(userId, rec) {
  console.log('Inserted recording..................');
});
```

Then I tried inserting directly into the database via `meteor mongo` and my hook was never called.

Is that expected behaviour?

**Comment by rclai** [comment]
It won't work if you do mongo operations directly in the mongo shell.

**Comment by francisbyrne** [comment]
Gotcha, thanks.

**Comment by rclai** [comment]
You might be able to use Meteor's observe APIs to do something, at least after an operation.
