### ISSUE TITLE
Firefox console warning about slow performance

### ISSUE THREAD

**Issue by bluebay** [matb33/meteor-collection-hooks#115]
Firefox console is throwing this warning:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

and the warning is regarding the line 
    Object.setPrototypeOf(instance, constr.prototype);   // 176

**Comment by matb33** [comment]
Thanks for the issue report! This is an unfortunate consequence of how Meteor approached their Meteor.users collection instantiation. By the time we can wrap collections, Meteor.users has already been instantiated.
