### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by dalgard** [matb33/meteor-collection-hooks#116]
The README file with the hooks reference contains wrong semantics in the code examples that follow each section from **.after.remove** onwards.

The examples read `test.after.remove: function (userId, doc) {` where they should be reading `test.after.remove(function (userId, doc) {`.

Thanks for the good work!

**Comment by matb33** [comment]
Oops... thanks for catching that... I can't believe I've had that mistake in there for so long!
