### ISSUE TITLE
collection2: Bypass all validation and hooks

### ISSUE THREAD

**Issue by theduke** [matb33/meteor-collection-hooks#120]
I'm using collection-hooks with https://github.com/aldeed/meteor-collection2 and I'm trying to figure out a way to bypass both Collection2 validation and the hooks.

When using MyCollection._collection.insert() the hooks fire.
When using MyCollection.direct.insert() the Collection2 validation runs.

Any ideas for this?
(As a workaround I resorted to using MyCollection.rawCollection())

Also created an issue at collectio2: https://github.com/aldeed/meteor-collection2/issues/224

**Comment by matb33** [comment]
I think the best way to do this is having collection hooks integrate with collection extensions, which will allow this soon: https://github.com/rclai/meteor-collection-extensions/issues/3

**Comment by alanning** [comment]
I think this issue can be closed as it seems there are two ways to do this:

1. `MyCollection.rawCollection()`

2. https://github.com/aldeed/meteor-collection2/issues/224#issuecomment-129020005

**Comment by matb33** [comment]
Agreed, thanks @alanning
