### ISSUE TITLE
Problem with "collection2, simpleSchema and autoForm" when validation error (still ruining)?

### ISSUE THREAD

**Issue by thearabbit** [matb33/meteor-collection-hooks#121]
I use `collection2, simpleSchema and autoform`, and then I add  `collection-hooks`.
I want to track events when collection is inserted or updated like this:

``` js
Collection.Customer.before.insert(function (userId, doc) {
    Events.trackInsert({
        description: doc
    });
});

Collection.Customer.before.update(function (userId, doc, fieldNames, modifier, options) {
    Events.trackUpdate({
        description: modifier
    });
});
```

When `autoform` have error (validation) to insert, the `collection hooks` still run `befor...`.
And then I tried use `after...` of `collection hooks`, but have the same problem. 
please help me.

**Comment by yuomtheara** [comment]
I use it on `client).

**Comment by zimme** [comment]
Same as #153, closing this as it's more info in that issue.
