### ISSUE TITLE
Incompatible with meteor-starter

### ISSUE THREAD

**Issue by femiveys** [matb33/meteor-collection-hooks#125]
Steps to reproduce:
- `git clone https://github.com/yogiben/meteor-starter.git myapp`
- `cd myapp`
- `meteor`
- Site loads well at localhost:3000
- `meteor add meteor-collection-hooks`

Then I get this error:
Your app is crashing. Here's the latest log.

Meteor._wrapAsync has been renamed to Meteor.wrapAsync

/home/femi/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Tabular.Table options must specify collection
    at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
    at packages/yogiben:admin/lib/both/startup.coffee:89:27
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at adminCreateTables (packages/yogiben:admin/lib/both/startup.coffee:66:4)
    at __coffeescriptShare (packages/yogiben:admin/lib/both/startup.coffee:114:2)
    at /home/femi/Dropbox/IT Simply Works/Klanten/www/a/.meteor/local/build/programs/server/boot.js:229:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by matb33** [comment]
Did you try with: `meteor add matb33:collection-hooks`? I'm actually not sure what will get loaded with `meteor add meteor-collection-hooks` to be honest...

**Comment by femiveys** [comment]
This gives me exactly the same error.

**Comment by rclai** [comment]
Are you on an old browser?

**Comment by femiveys** [comment]
No, latest chrome. But the error also appears several times in the console.

**Comment by matb33** [comment]
You'll need to edit `.meteor/packages` and move the reference for `matb33:collection-hooks` further up the top, as long as it's above the `comments` package. We haven't figured out a way around this issue, and is actually a main driver towards implementing collection hooks into core (or having a core collection extension API).

**Comment by femiveys** [comment]
I can confirm this works perfectly. Thanks a lot.
The actual goal was socialize:friendships which depends on socialize:base-model, which depends on matb33:collection-hooks.
With this workaround, this works as well.
