### ISSUE TITLE
Set the website of this GitHub repo to the Atmopshere package

### ISSUE THREAD

**Issue by dandv** [matb33/meteor-collection-hooks#127]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by matb33** [comment]
Alright alright I'll get 'er done :)

**Comment by matb33** [comment]
Finally took care of it. Many apologies for the delay @dandv!
