### ISSUE TITLE
Run both on ".before.insert() and before.update()" when I insert data in autoform???

### ISSUE THREAD

**Issue by thearabbit** [matb33/meteor-collection-hooks#129]
I use `collecion2, simple schema, auto form and collection-hook`.
```js
// Server
Customer.before.insert(function (userId, doc) {
    console.log('before insert');
});
Customer.before.update(function (userId, doc, fieldNames, modifier, options) {
    console.log('before update');
});
```
Collection-Hook run both in `.before.insert() and before.update()` when I insert data in autoform.
Please help me.

**Comment by Adam-Goldman7** [comment]
I experience the same things with after.insert and after.update

**Comment by matb33** [comment]
That simply means that one of those packages is running insert and then update. There's no magic going on as far as collection hooks go.

**Comment by Adam-Goldman7** [comment]
Maybe add this to documentation so future users won't ask the same?

**Comment by sean-stanley** [comment]
Another option is seeing if we can make this package cooperate with collection2 and/or autoform to optionally ignore hooks
