### ISSUE TITLE
Cursor observations

### ISSUE THREAD

**Issue by 57even** [matb33/meteor-collection-hooks#132]
I really like the package but I wonder if there is anything that can be done using this package which cannot be done using cursor observations (`Cursor.find().observe()`)?

**Comment by cristo-rabani** [comment]
57even , This package is more efficient than observations and if you don't need react on changes from outside meteor (directly on db). This is better way

**Comment by matb33** [comment]
@57even, running `before` hooks for example

**Comment by dropfen** [comment]
Hmm, but just a though..

Cursor.observe() can be used anywhere.. this package has to be used on the same instance the where the action happens, right?
