### ISSUE TITLE
Meteor.users.after.insert isn't called on account creation

### ISSUE THREAD

**Issue by elie222** [matb33/meteor-collection-hooks#135]
I realise that there's the Accounts.onCreateUser method, but this can only be called once, and is called before the user is created anyway.

I'm probably missing something. Here's my code:
```
Meteor.users.after.insert(function (userId, doc) {
  console.log('after insert user');
});
```
The log isn't printed to the console.

**Comment by heaven7** [comment]
Is this code on the client or on the server?

**Comment by chenrozenes** [comment]
I have the same problem.. On the server

**Comment by chenrozenes** [comment]
I have the same problem. On the server

**Comment by matb33** [comment]
What other packages are you using? It's likely some kind of package interference.

**Comment by alanning** [comment]
I just tested with a minimal app and confirmed that `Meteor.users.after.insert` is successfully called after `Accounts.createUser`.

I recommend closing this issue and re-opening if someone posts a repro.

**Comment by matb33** [comment]
Agreed, thanks @alanning for popping in and helping out -- much appreciated
