### ISSUE TITLE
After update hook for Meteor.users collection is not getting all the arguments

### ISSUE THREAD

**Issue by niranjans** [matb33/meteor-collection-hooks#138]
I am wondering if there is a special way to handle `Meteor.users` collection.

I tried doing this:

```
Meteor.users.after.update( function (userId, doc, fieldNames, modifier, options) {

    console.log("updating user ", userId, doc, fieldNames, modifier, options);
    
}, {fetchPrevious: false});
```

And I found that `modifier` and `options` is undefined every time I update the user profile object.

**Comment by matb33** [comment]
Fixed in 0.7.14 -- thanks for the report!
