### ISSUE TITLE
after.find NOT working as expected.

### ISSUE THREAD

**Issue by colus001** [matb33/meteor-collection-hooks#141]
Coffee
```
Collection.after.find((userId, selector, options, Cusor) ->
  options.fields = _.defaults(options.fields or {}) if options
  if not Meteor.isClient and not _.contains(_.values(options.fields), 1)
    if _.find(Cusor.fetch(), (item) -> item.ownerId isnt userId and not item.isVisible)
      _.extend(options.fields, 'products.amount': 0)
)
```

JS
```
Collection.after.find(function(userId, selector, options, Cusor) {
  if (options) {
    options.fields = _.defaults(options.fields || {});
  }
  if (!Meteor.isClient && !_.contains(_.values(options.fields), 1)) {
    if (_.find(Cusor.fetch(), function(item) {
      return item.ownerId !== userId && !item.isVisible;
    })) {
      return _.extend(options.fields, {
        'products.amount': 0
      });
    }
  }
});
```

I'm using after.find to remove products' amount field. But it doesn't work as expected. For example, it sometimes remove and sometime not. Especially when you go back and forward on browser, it shows different result with same behaviour.

I first found out this issue ip cross browser reactivity issue. for example if you hide something, it doesn't give the result of options.fields. But the code actually works. I mean I did console.log 'hiding' and it logs properly. I'm not sure what this is about. 

We're using FlowRouter and maybe related?

**Comment by matb33** [comment]
This doesn't sound like a good use case for collection hooks. I suggest you take a look at the built-in `fields` option for `find`, which is especially effective within a `Meteor.publish` at hiding fields from the client.
