### ISSUE TITLE
incompatible with ground:db

### ISSUE THREAD

**Issue by Jehu** [matb33/meteor-collection-hooks#146]
Can't create a client-side-only Ground.Collection, if matb33:collection-hooks is installed.
Get always the error ``Error: use "new" to construct a Mongo.Collection``

ground:db is awesome for pure offline apps. So it would be nice to get the two packages work together.

**Comment by fschaeffler** [comment]
You probably already found another solution. However, this answer is for everyone who's look for a fix, too. Just manually place the package for `matb33:collection-hooks` as the very first one on `.meteor/packages`.

**Comment by Jehu** [comment]
@fschaeffler thank you
