### ISSUE TITLE
Each documents of collection can attach some default values while insert or update

### ISSUE THREAD

**Issue by crapthings** [matb33/meteor-collection-hooks#15]
i always add createdAt, createdBy, timestamp and such keys on each 'collection.before.insert' like

```
Projects.before.insert (userId, project) ->
    project.createdAt = new Date()
    project.timestamp = Date.now()
    project.creatorId = Meteor.userId()
    project.createdBy = Meteor.user().username

Tasks.before.insert (userId, task) ->
    task.createdAt = new Date()
    task.timestamp = Date.now()
    task.creatorId = Meteor.userId()
    task.createdBy = Meteor.user().username
```

but some collections do not need attaching

Could we add some feature like we can allow some collections do attach default values ?

maybe something like

```
[Projects, Tasks].before.insert (userId, doc) ->
    doc.createdAt = new Date()

[Projects, Tasks].before.update (userId, doc) ->
    doc.updatedAt = new Date()
```

**Comment by scottsimock** [comment]
@matb33 Do you have any sample CollectionManager code to share? I think this is exactly what I'm looking for and would be interested to see how you implemented.

**Comment by matb33** [comment]
@scottsimock unfortunately I wrote that only as an example, but it shouldn't be too hard to write. That being said, there are a ton more options around these days. There may be a smart package that does this by now

**Comment by scottsimock** [comment]
@matb33 Thanks for the quick reply. Believe I'm overthinking the CollectionManager. You're just suggesting its code that calls new Mongo.Collection plus other collection setup code like collection-hooks. I was thinking it was a superclass above Mongo.Collection. Thanks again!
