### ISSUE TITLE
Hook options not passed as argument to hook

### ISSUE THREAD

**Issue by fvilers** [matb33/meteor-collection-hooks#155]
I'm trying to use hook options as documented:

    testCollection = new Mongo.Collection("test");
    testCollection.hookOptions.after.update = {exampleOption: 1};
    testCollection.after.update(onUpdateHook);

My hook function:

    onUpdateHook = function (userId, doc, fieldNames, modifier, options) {
      console.log(options);
    }

The output is: {}

Any chance I'm doing something wrong here?

**Comment by fvilers** [comment]
For testing purposes, I've created a demo app at: https://github.com/fvilers/meteor-collection-hooks-issue-155

**Comment by matb33** [comment]
These options aren't passed down to hooks -- they are configuration options, and currently only `fetchPrevious` is implemented. Sorry for the confusion

**Comment by fvilers** [comment]
Would you support passing an arbitrary object as options, in a near future?

**Comment by matb33** [comment]
I'm not sure, perhaps -- can you provide an example use case? Perhaps there's already a way, and regardless this would help me wrap my head around why it would be needed

**Comment by fvilers** [comment]
I want to use an hook to notify an event bus that a document has been inserted/updated. The options object I was thinking of is the name of the related event + some args (maybe the document itself).

So, I tried to write this:

	Orders = new Mongo.Collection("orders");
	Orders.hookOptions.all.all = { name: "orders" };
	Orders.after.insert(function (userId, order, fieldNames, modifier, options) {
		eventBus.publish(options.name, "inserted", { document: order });
	});
	Orders.insert({ foo: "bar" });

**Comment by matb33** [comment]
You might have some luck digging up the collection name within the hook callback by digging through the `this` object. It'll at least have: `{context: self, _super: _super, args: args}`

**Comment by fvilers** [comment]
I've already searched through private properties, but I'll take a second look asap.

Thanks,
Fabian
