### ISSUE TITLE
after.insert that follows an upsert doesn't get the doc 

### ISSUE THREAD

**Issue by inbaldoron** [matb33/meteor-collection-hooks#156]
when doing an upsert that turns out to be an insert, the after.insert is triggered (as I understand is the correct behaviour from issue #16)  but the doc argument just contains the id and not the entire inserted document

**Comment by zhaoyao91** [comment]
+1, I meet the same problem.

**Comment by gfmr90** [comment]
+1, I have the same problem too

**Comment by inbaldoron** [comment]
Thanks for the fix
