### ISSUE TITLE
Get query that initialized the operation

### ISSUE THREAD

**Issue by xpluscal** [matb33/meteor-collection-hooks#160]
HI!

Is it possible to retrieve the query that initialized the operation?
Say I choose to update all objects in a collection by their "reference"-field. Can I get the infor that i queried the "reference"-field from the after.update function?

Thanks in advance.

**Comment by matb33** [comment]
Could you look at fieldNames or modifier to infer this information?

**Comment by alanning** [comment]
The options that you pass to your update function are also passed through to your after handler.  So you could do something like this:

```
var query = {reference: "foo"};
var update = {$set: {a: 1}};
var options = {multi: true, query: query};
Entries.update(query, update, options);

Entries.after.update(function (userId, doc, fieldNames, modifier, options) {
  var query = options.query;
  // query => {reference: "foo"}
});
```

**Comment by matb33** [comment]
Good idea @alanning
