### ISSUE TITLE
No `this.transform()` method in before upsert hook

### ISSUE THREAD

**Issue by gsuess** [matb33/meteor-collection-hooks#161]
In the readme it explicitly says that the `transform()` function is available in the before upsert hook

> `this.transform()` obtains transformed version of document, if a transform was defined.

However attempting to call that method gives:

```
TypeError: Object [object Object] has no method 'transform'
```

**Comment by matb33** [comment]
Thanks, will look at this ASAP

**Comment by zimme** [comment]
I've created a PR that makes `this.transform()` available in `before.upsert` in the case when the `selector` will match documents in the collection. In the case when the `selector` doesn't match any documents `this.transform()` won't be available.

**Comment by zimme** [comment]
This is merged, so you will have `this.transform()` available if it's been defined and if `selector` matches any documents.

**Comment by zimme** [comment]
I've reverted the commits that would make this available.

As the `before.upsert` hooks run once and not once per matched document the changes would actually change when and how `before.upsert` run.

What you can do instead is to use the `selector` and find the documents and for each document apply it's transform and do what you needed.
