### ISSUE TITLE
Accessing nested field in fieldNames when using before.update hook

### ISSUE THREAD

**Issue by nabiltntn** [matb33/meteor-collection-hooks#162]
Hi,
When using the before update hook with a nested update like this:
`collection.update({_id : 'dddddd'},{$set : {'parentProp.child1' : true}});`

fieldNames inside
`collection.before.update(function(userId, doc, fieldNames, modifier, options) {
});`
does not contain full property path : **parentProp.child1** but only **parentProp**

**Comment by javierocanas** [comment]
```
collection.before.update(function(userId, doc, fieldNames, modifier, options){
  modifier.$set = modifier.$set || {};
  modifier.$set.parentProp = {child1:true};
})
```
Good vibes.

**Comment by matb33** [comment]
I mimicked what Meteor does in their Allow/Deny API, and lifted their function to get the `fieldNames`. I'll be sticking with this for the foreseeable future since it matches an existing similar Meteor API
