### ISSUE TITLE
Performance warning

### ISSUE THREAD

**Issue by ulerch** [matb33/meteor-collection-hooks#163]
The following warning is displayed in the console:

<code>mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create</code>

**Comment by daveyshindig** [comment]
This is happening for me, too.

**Comment by matthieuh** [comment]
+1

**Comment by matb33** [comment]
Unfortunately this is the case...
