### ISSUE TITLE
How do we validate docs in an upsert?

### ISSUE THREAD

**Issue by trusktr** [matb33/meteor-collection-hooks#168]
I'm making my own custom validation logic (i.e. *not* using collection2, etc). I can easily validate documents on `.before.insert` and `.before.update` by checking the document, then simply returning false if validation fails.

But with `.before.upsert` the handler function doesn't have a `doc` arg. How might I be able to validate the documents added or the document inserted in an upsert?

**Comment by trusktr-goin** [comment]
@matb33?

**Comment by trusktr-goin** [comment]
Solved: https://github.com/matb33/meteor-collection-hooks/issues/169#issuecomment-193050902
