### ISSUE TITLE
How do we apply a hook to all collections?

### ISSUE THREAD

**Issue by trusktr** [matb33/meteor-collection-hooks#170]
Is it `CollectionHooks.before.<hookName>(function() {...})`?

**Comment by crapthings** [comment]
+1 how to do it ?

    _.each([Meteor.users, Products, Posts, Items], function(collection) {
        collection.before.insert();
    });

**Comment by trusktr** [comment]
@crapthings That definitely works. I also just looked and see this: https://github.com/matb33/meteor-collection-hooks/blob/master/collection-hooks.js#L10-L15

Looks like we can put stuff in the defaults property there.

**Comment by trusktr** [comment]
@matb33 ?

**Comment by bilics** [comment]
+1 - How can I do this ?

**Comment by matb33** [comment]
Agreed this would be useful

**Comment by matb33** [comment]
Duplicate of https://github.com/matb33/meteor-collection-hooks/issues/110
