### ISSUE TITLE
Add cursor to before.find and before.findOne

### ISSUE THREAD

**Issue by Kolorbon** [matb33/meteor-collection-hooks#171]
Being able to get and manipulate the cursor of before.find and before.findOne would be really useful, especially for a package like [Planifica/encryption](https://github.com/Planifica/encryption). As in Planifica/encryption#9 it's needed to decrypt and filter documents.

Would it be possible to implement it?

**Comment by matb33** [comment]
I don't think the cursor would even be available at that point... I can see the use case, but it's just not going to work since before.find and before.findOne occur _before_ find
