### ISSUE TITLE
before.update doc is old doc before updates? Or is doc the new doc as will be saved?

### ISSUE THREAD

**Issue by trusktr-goin** [matb33/meteor-collection-hooks#179]
I'd like to validate `doc` on `before.update`, but apparently `doc` is the old `doc` before the `modifier` is applied to it. How do we validate the new doc?

**Comment by trusktr-goin** [comment]
Answer: use `LocalCollection` from `minimongo`:

```js
LocalCollection._modify(doc, modifier)
```

That modifies the doc in place, and then we can perform checks on it's new modified state.

**Comment by matb33** [comment]
Yep... https://github.com/matb33/meteor-collection-hooks/issues/91#issuecomment-85007712
