### ISSUE TITLE
Tests fail drastically when collection hooks is added

### ISSUE THREAD

**Issue by mitar** [matb33/meteor-collection-hooks#19]
Meteor official tests fail drastically when collection hooks package is added. This simply means that collection hooks are not suitable for production. Tests should not be failing. Using a default project created by `meteor create`, adding packages:
- standard-app-packages
- autopublish
- insecure
- preserve-inputs
- collection-hooks
- accounts-base

Run `mrt test-packages` and open browser. You will get a long list of tests which failed:

```
tinytest - accounts - expire numeric token
tinytest - passwords - basic login with password
tinytest - passwords - plain text passwords
tinytest - passwords - changing passwords
tinytest - passwords - new user hooks
tinytest - passwords - Meteor.user()
tinytest - passwords - allow rules
tinytest - passwords - tokens
tinytest - accounts emails - reset password flow
tinytest - accounts emails - verify email flow
tinytest - accounts emails - enroll account flow
tinytest - collection - update options, STRING
tinytest - collection - update options, MONGO
```

Without this package added tests work correctly.

**Comment by rclai** [comment]
Lol, this thread was funny to read.

**Comment by mitar** [comment]
Ah, tests. We developed this [package to make such tests easier](https://github.com/peerlibrary/meteor-classy-test). It wraps Tinytest with helpful stuff. The main one I think for any database-based package is that you can interleave server and client test. You make something on the client, check on the server, go back to client, etc.

**Comment by mizzao** [comment]
I have a similar approach to that for setup/teardown methods, for example: 

https://github.com/HarvardEconCS/turkserver-meteor/blob/master/tests/utils.coffee#L26
