### ISSUE TITLE
Question: Is it possible to pass parameter from update to collectionHook?

### ISSUE THREAD

**Issue by thebarty** [matb33/meteor-collection-hooks#192]
Hi guys,

Is it possible to pass parameter from update to collectionHook?

This would be really handy for my useCase. Something like this:

```
// pass a parameter to on update that I can then read in hook
Collection.update(id, {$set: { something: 'new } }, { parameterForCollectionHook: 'coming from mars' } )

// read this parameter in hook, p.e.
Collection.after.update( (parameterForCollectionHook) => {
  console.log(parameterForCollectionHook)
})
```

Is there any chance to do this?

**Comment by nicooprat** [comment]
Absolutely:

````js
Posts.update(_id, {
  $set: {
    title: 'test'
  }
}, {myOption: false});
````

And then:

````js
this.collection.before.update((userId, doc, fieldNames, modifier, opts) => {
  if( opts.myOption ) {
    ...
  }
});
````

I think it's not possible with `insert` or `remove` though (for now?).

**Comment by zimme** [comment]
@nicooprat's answer is correct, and the reason `insert` and `remove` doesn't accept options is because the original api doesn't have options as arguments.
