### ISSUE TITLE
Transition to npm?

### ISSUE THREAD

**Issue by nmaro** [matb33/meteor-collection-hooks#199]
Are there any plans to transition this package to npm?

**Comment by namirsab** [comment]
As long as this package depends on atmosphere packages, it's not possible to fully move it to npm i'm afraid.

**Comment by zimme** [comment]
From what I've seen so far with Meteor packages and npm you can only check if an atmosphere package is available but not depend on it so I don't see this package moving to npm until all it's atmosphere dependencies are also available on npm.
