### ISSUE TITLE
Can hook be called from Robomongo event?

### ISSUE THREAD

**Issue by petr24** [matb33/meteor-collection-hooks#209]
Is it possible to have a collection hook trigger when an action is performed via Robomongo?

For instance, if I remove a document from Robomongo the collection hook does nothing. 
However I have some server side observers for custom added/changed/removed and those get triggered when I do something via Robomongo. Not sure if this package can catch that same event. And the observers that I have only observe a subset of data so I can't rely on that for what I want.

Thanks.

**Comment by matb33** [comment]
Unfortunately not. Collection hooks are wrapping method calls, not actually watching the database itself. With server-side observeChanges, I believe you could do what you want.

**Comment by petr24** [comment]
Gotcha, Thanks! Great package regardless.
