### ISSUE TITLE
Difference between anonymous user and server-invoked operation?

### ISSUE THREAD

**Issue by Kshatra** [matb33/meteor-collection-hooks#212]
How can i differentiate between anonymous user and server-invoked operation in a hook? In both cases userId would not be defined. I'm trying to use hooks as permission filter to lessen permission check code in each publication/method (is this a good idea?)

For example, i have a server code that make some collection operations on each start of the server. But anonymous users cannot be allowed to make these operations. How to write an operation hook in this case?

**Comment by zimme** [comment]
First thing that comes to mind is some package that assigns anonymous users to non-logged in users and with that package you should be able to differentiate between server- and anonymous-invoked operations.
