### ISSUE TITLE
Hooks are not fired for aggregation

### ISSUE THREAD

**Issue by lijoantony** [matb33/meteor-collection-hooks#217]
I am filtering out some data in find/findOne queries with the help of hooks, for security purposes. I found that find hooks are not fired during an aggregate operation (via meteor-aggregate pkg). Is this the expected behaviour? Is there a work around to achieve the same? If it is a missing feature, is there a plan to support the same in future?

**Comment by zimme** [comment]
Yes, there's nothing we can do about that because `Collection.aggregate` is bound to `rawCollection` which is the collection representation created by the mongodb node driver.

We are just working with the Meteor abstraction of the collections. Which is on a layer higher up than the rawCollection.
