### ISSUE TITLE
after.insert is async?

### ISSUE THREAD

**Issue by stefanocudini** [matb33/meteor-collection-hooks#226]
hi

This is really amazing and useful meteor pkg congrats @matb33 !

I'm using it to perform caching operations for subfields of documents I was wondering if
if any *Collection.update(...);* inside the after.insert callback is an asynchronous operation or Or I have to do this to get this:

```javascript
Collection.after.insert(function(id){
  Meteor.defer(function(){
   Collection.update(id, {$set: ... });
  })
});
```

**Comment by micahalcorn** [comment]
In my experience, the callbacks are synchronous.

**Comment by zimme** [comment]
Yes, they are sync for now. There is currently a discussion in #229 about this also. Thinking about adding support for returning a promise from a hook and wait for that before continuing on to the actual method.

**Comment by stefanocudini** [comment]
ok tnk!
