### ISSUE TITLE
arrow function doesnt get binded with this.previous

### ISSUE THREAD

**Issue by sirpy** [matb33/meteor-collection-hooks#242]
When using an arrow function:
 (userId,doc..) => {}, this.previous is not defined
function(userId,doc...) {} works just fine

**Comment by zimme** [comment]
Yeah, that's how arrow functions work... Arrow functions don't have their own `this` and can't be given (bound) a new this value, it always uses the `this` in the context of where it's defined.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

Here you can read up on arrow functions.
