### ISSUE TITLE
Callback of a direct update forces direct on operations within callback

### ISSUE THREAD

**Issue by evolross** [matb33/meteor-collection-hooks#243]
Version: `matb33:collection-hooks@0.9.0-rc.4`

Just reporting for the heck of it - I know this really isn't supported anymore, but it works for the most part. If I get time I may try to work on this.

In server code I have:
```
someCollection.direct.update({...}, function(error) {
   if(!error) {
      anotherCollection.update({...});
   }
});
```

The update to `anotherCollection` gets the `direct` bypasser _forced_ onto it.

**Comment by zimme** [comment]
Haven't looked at the cose for a while, but thinking that some fiber environment variable is being set and as the update on anotherCollection is run in the same fiber or a cloned fiber environment it also runs in direct mode.

But not sure

**Comment by evolross** [comment]
Just ran into this again... and figured something out as a work-around/solution (after a lot of shots in the dark). If you throw in a `CollectionHooks.directEnv = new Meteor.EnvironmentVariable(false)` like so:
```
someCollection.direct.update({...}, function(error) {
   if(!error) {
      CollectionHooks.directEnv = new Meteor.EnvironmentVariable(false);
      anotherCollection.update({...});
   }
});
```
It disregards the `direct` on the second update.  Thanks for the advice. It was indeed a fiber environment variable.
