### ISSUE TITLE
Exception in delivering result of invoking

### ISSUE THREAD

**Issue by wI2L** [matb33/meteor-collection-hooks#29]
Hey.

I am getting this exception while using an after.insert hook, but the callback is well executed tho. Is this a bug inside the package, or am i using it badly ?

<pre><code>
Exception in delivering result of invoking '/vservers/insert': TypeError: Object #<Object> has no method 'apply'
    at http://localhost:3004/packages/collection-hooks.js?8023554a1294990dd1d66365a38eff93f309ce75:228:22
</code></pre>

**Comment by the1mills** [comment]
I am having a problem with this - same cryptic error message...
