### ISSUE TITLE
Meteor.users no longer an instance of Meteor.Collection

### ISSUE THREAD

**Issue by dburles** [matb33/meteor-collection-hooks#34]
Without collection-hooks:
`
Meteor.users instanceof Meteor.Collection
 => true
`

With collection-hooks:
`
Meteor.users instanceof Meteor.Collection
=> false
`

The problem with this now is that any Meteor.Collection.prototype.fn we wish to attach does not attach to the Meteor.users collection. This affects the [collection-helpers](https://github.com/dburles/meteor-collection-helpers) package and potentially others.

https://github.com/dburles/meteor-collection-helpers/issues/2

**Comment by leducqui** [comment]
@matb33  I meet same issue on IE10, on Chorme, IE11, the website work fine. How to fix it?
