### ISSUE TITLE
Question on designing hooks

### ISSUE THREAD

**Issue by geekyme** [matb33/meteor-collection-hooks#55]
I have a particular use case where a collection has different update operations on it. Each update operation should trigger a different hook. Eg. Liking a document, editing the timestamp, raising a flag, adding collaborators, etc. 

At the moment, in my hooks I have to validate fields / modifiers to determine which operation is running. This becomes very hard to maintain in the long run and I am wondering whether there is a better way to design my hooks.  

Or should I just fall back to writing my own meteor method instead?

**Comment by matb33** [comment]
Looking back at this, as cool as this would be, it'd be quite the job to pull this off and not sure it'd be worth bringing this much change to collection-hooks at this point. I'm not even sure if this API would work, considering my previous note on how it also needs to support synchronous calls.
