### ISSUE TITLE
TypeError: Cannot call method insert of undefined

### ISSUE THREAD

**Issue by boustanihani** [matb33/meteor-collection-hooks#56]
I am getting => `TypeError: Cannot call method 'insert' of undefined`

``` javascript
IMAGES = new Meteor.Collection('images');

IMAGES.before.insert(function(userId, doc) {
    //...
});
```

I am using Meteor 0.8.3 and the packages Autoform, Collection2 & SimpleSchema...
Does this package conflict with the mentioned above ??

**Comment by maxnowack** [comment]
In my case it was related to #62
