### ISSUE TITLE
TypeError: Cannot call method 'insert' of undefined

### ISSUE THREAD

**Issue by dalgard** [matb33/meteor-collection-hooks#76]
It seems like the `collection-hooks` package somehow isn't properly applied. I've removed all other 3rd party packages from the project and the only active code is this:

``` javascript
Projects = new Mongo.Collection("projects");

Projects.before.insert(function () { ... });
```

What gives? I've recently upgraded Meteor and packages to newest versions. How to troubleshoot? Thanks.

**Comment by daslicht** [comment]
Any fix for this ? 
We get the same error :  
http://pastebin.com/w8rcby85

**Comment by ibussieres** [comment]
This might sound stupid, but for me, it was simply because I am using package file structure and hadn't added `matb33:collection-hooks` to package.js dependencies.

**Comment by nicejwjin** [comment]
I don't think this question is matched perfectly but argument of '.before.findOne (userId, selector, options)  -> ' functions are all undefined, {} something like that even the findOne's result was fine. I can't catch anything for these stupid situations..

**Comment by monkeydri** [comment]
Ran into this issue suing meteor 1.8.

Tried to use version 0.9-rc4 (from the github repo) but got the same error. Any clue ?
