### ISSUE TITLE
Consider sugaring for more uniform API

### ISSUE THREAD

**Issue by dalgard** [matb33/meteor-collection-hooks#80]
When writing `deny` and `allow` rules, the signature looks like this:

```javascript
collection.allow({
  insert: function (user_id, doc) { ... }
});
```

Would you consider overloading the API of `collection-hooks` so that instead of a plain object, the `before` (and `after` and so on) property was a function which took a dictionary in the same manner as `allow`?

Since functions are also objects, the current API could go on completely unchanged – the new function would just be some sugar, passing things on to its own sub-method.

I would look more pretty and be less confusing, I think:

```javascript
collection.before({
  insert: function (user_id, doc) { ... }
});
```

&nbsp;
Just to make clear what I mean, the implementation would look something like this:

```javascript
Mongo.Collection.prototype.before = function (dict) {
  Object.keys(dict).forEach(function (key) {
    var method = this.before[key];
    if (typeof method === "function") method(dict[key]);
  });
};

Mongo.Collection.prototype.before.insert = function (callback) { ... };

...
```

**Comment by matb33** [comment]
I'll leave this design decision to Meteor core devs should they choose to eventually roll collection hooks into core.
