### ISSUE TITLE
Multiple Collection.before.update() declarations

### ISSUE THREAD

**Issue by evliu** [matb33/meteor-collection-hooks#81]
I was wondering if there was a way to append more functions to be run on `someCollection.before.update(myFunction)`. I'm writing a package to extend a framework that already declares a `before.update` action and I don't want to overwrite it, but add to it. Thanks!

**Comment by cyclops24** [comment]
@evliu what about `after.update`? Can we use multiple after hook on a collection?

**Comment by cyclops24** [comment]
@evliu My question related to this:
https://github.com/matb33/meteor-collection-hooks/issues/205
