### ISSUE TITLE
executing code before an autoform update

### ISSUE THREAD

**Issue by ZHosseinpour** [matb33/meteor-collection-hooks#82]
I want to do something before an autoform update occur . i use ' coll.before.update ' to execute my logic in its function but the callback function dos not execute even though the update occur . i don't know where i made mistake or if anything else i should do.
this is my code:

    ads.before.update(function(userId, doc,fieldNames, modifier, options) {
     console.log("doc");
     doc.img = Session.get("imgAds");
     // doc.linkItem=Session.get("itmId")
     });

**Comment by matb33** [comment]
Are you still having an issue or have you resolved it?

**Comment by ZHosseinpour** [comment]
My problem was solved,thanks.
