### ISSUE TITLE
delete user, and all documents entered by the user deleted

### ISSUE THREAD

**Issue by Ethaan** [matb33/meteor-collection-hooks#83]
So let us take the following scenario, a user is deleted by the administrator (currently using the meteor-roles from alanning), so for now just 1 user with the -admin- role can view and delete users, So far so good but the problem is that the user that was deleted, was owner of posts and comments within the APPLICATION (Mongo separate collections), then I try to figure how to do a hook before.remove but honestly I feel a little lost, just me would like to know first if this is possible with this package and second a small guide on how to do it (do not ask all code, but simply a reference, perhaps a question or idk sO)

this is my simple delete code,
```javascript
Template.crearUsuarios.events({
'click #deleteUser' : function(event,template){
 var idUsuario= this._id;
 Meteor.call('deleteUser',{_id:idUsuario})
 }
});
```
and this is the simple server method
```javascript
Meteor.methods({
 deleteUser : function(id){
    return Meteor.users.remove(id);
  }
})
```
As I said my templates are protected by the moment with {{if}} IsInRole from allaying package, also insecure and autpublish package was removed so my template```javascript crearUsuario``` is like a "admin backend" .

so how can i use this package to accomplish that? deleting user and all documents entered by delete user

Also all comment and post have a ownerId field, so thats the way i connect the user with the document

thanks in advice

**Comment by Ethaan** [comment]
Ok so i remove the meteor call and use the allow/deny, now i need to set my after.remove on the server side correct?

**Comment by matb33** [comment]
Yep

**Comment by Ethaan** [comment]
ok so this is how my code looks 
My Method to delete posts
```javascript
Meteor.methods({
  borrarAdopcionUsuario:function(){
    Adopcion.remove({});
  }
})
```
My allow on the server side
```javascript
Adopcion.allow({
  remove: function(userId, doc) { return doc.allowed;},
});
```
And my event to delete user and all document owned by that user
```javascript
Template.editarUsuario.events({
  'click #borrarPerfil' : function(){
    var mensaje = confirm('estas seguro que deseas borrar tu perfil?')
    if(mensaje === true){
          var idUsuario= this._id;
         Meteor.users.remove({_id:idUsuario},function(error,succes){
           if(error){
             console.log(error.reason)
           }else{
             Meteor.call('borrarAdopcionUsuario',function(error,result){
               function borraComentarios(){
                 var count = Adopcion.find({'metadata.authorId': Meteor.userId}).count();
                 Adopcion.remove({'metadata.authorId':idUsuario},function(errorRemove){
                   if(errorRemove){
                     console.log(errorRemove.reason)
                   } else{
                     console.log("se borraron los post de adopcion del usuario")
                   }
                 });
               }
             })
             Router.go('/usuarioBorrado')
           }
         })
    } else {
      console.log("no se borro nada")
    }
});
```

So when i test the code, i have 2 users;
User 1 ,User 2,
so when i deleted the User1
All documents from user1 and user2 got deleted, so i think its my remove function,

**NOTE** im using FSCollection, but i guess its the same as a normal collection, also im looking at[this](https://github.com/matb33/meteor-collection-hooks/blob/master/tests/remove_allow.js)
example
Thanks for the support

**Comment by Ethaan** [comment]
sorry for the spam, but i have a doubt.
 why this event works

```javascript
Template.adoptarPage.events({
  'click #borrarPosts':function(){
    var findArchivosUsuario = Adopcion.find({'metadata.authorId': Meteor.userId()}).fetch();
    for(var i=0;i<findArchivosUsuario.length;i++){
      Adopcion.remove({_id:findArchivosUsuario[i]._id});
    }
  }
})
```

But when i call it on the delete user callback don't works? im doing it wrong?
```javascript
Template.editarUsuario.events({
  'click #borrarPerfil' : function(){
    var mensaje = confirm('sure you want to delete this profile?')
    if(mensaje === true){
      var idUsuario= this._id;
      Meteor.users.remove({_id:idUsuario},function(error,succes){
        if(error){
          console.log(error.reason)
        }else if(succes){
         Meteor.users.after.remove(function (userId, doc) {  
         var findArchivosUsuario = Adopcion.find({'metadata.authorId': Meteor.userId()}).fetch();
              for(var i=0;i<findArchivosUsuario.length;i++){
                  Adopcion.remove({_id:findArchivosUsuario[i]._id});
                  console.log(findArchivosUsuario[i]._id)
                }
         });
        }
      });
    }              
  }
});
```
its that the correct way to call after.remove?
