### ISSUE TITLE
collection.direct.update(id, ...) doesn't work

### ISSUE THREAD

**Issue by rclai** [matb33/meteor-collection-hooks#89]
Is this intentional? Vanilla Meteor ```collection.update``` lets you pass in an ID.

I had to explicitly pass ```{ _id: id }``` when using ```collection.direct.update```.

**Comment by matb33** [comment]
Are you using the latest version of collection-hooks? I just wrote an additional test to verify this behavior and with the latest version, it passed

**Comment by flean** [comment]
Same issue with me. v 0.7.9

**Comment by matb33** [comment]
I wrote tests in 0.7.10 (unpublished) that verify that it works, so I must be missing something. Can any of you provide a sample that reproduces the issue?

**Comment by rclai** [comment]
Okay, coming right up.

**Comment by rclai** [comment]
Here it is: https://github.com/rclai/collection-hooks-direct-update-issue

**Comment by matb33** [comment]
Ah I see why my test didn't catch it... I'm setting connection: null when creating the test collection out of simplicity, which I believe then uses the minimongo driver on the server too... I'll take a look ASAP

**Comment by matb33** [comment]
Just FYI, I spent a bit of time on this and it's a tough one to fix. I'll get back to it as soon as I can.

**Comment by rclai** [comment]
Ok np, I'll just `{ _id: 'specify this' }` for now on.
