### ISSUE TITLE
collection.direct.insert with collection2 / collection.direct inserts mongo style ObjectId

### ISSUE THREAD

**Issue by copleykj** [matb33/meteor-collection-hooks#90]
Using collection.direct.insert with collection2 and it seems that it is completely bypassing collection2 functionality. Not sure if this is intended behavior but would be nice to just skip the hooks and still have collection2 do validation.

Also when inspecting the record inserted with the direct functionality the record had an ObjectId instead of the string style ID that meteor uses which would lead to a mixed _id type for the collection.

**Comment by matb33** [comment]
This may be the same issue as in #89

**Comment by matb33** [comment]
Should be fixed (let me know if it isn't)
