### ISSUE TITLE
console.warn("Consider migrating from `new Meteor.Collection` to `new Mongo.Collection` in:", arguments.callee.caller);

### ISSUE THREAD

**Issue by nicolsondsouza** [matb33/meteor-collection-hooks#93]
It would be nice, if this warning would have been a bit smaller,
cause on every restart of the app, I get this warning and unable to code with mine.

**Comment by matb33** [comment]
I'm not sure what this has to do with this package -- I'm not emitting this warning

**Comment by mizzao** [comment]
This is a Meteor warning; you should replace all instances of `Meteor.Collection` in your code (and update any outdated packages).

**Comment by trinisofttechnologies** [comment]
Thanks the warning has been removed,
I will update the package and the warning will disappear.
