### ISSUE TITLE
Collection Hooks uses modifier from first document for all documents when an update is run with multi=true

### ISSUE THREAD

**Issue by todda00** [matb33/meteor-collection-hooks#94]
When collection hooks are in place and an update is run with the option multi=true, the modifier which is established in the first document is used for all documents. 

Example:
Say there is a collection named Jobs and it has a few fields, one of which is name. You write a hook to duplicate the name field to another field (this example could be anything else as well), it looks like this (coffeescript)
```
Jobs.before.update (userId, doc, fieldNames, modifier) ->
  modifier.$set = modifier.$set || {}
  modifier.$set.newField = doc.name
  return
```

There are a few documents that have entries like this:
```
Document 1
name: "Job1"
archived: true

Document 2
name: "Job2"
archived: true
```

If a query like this is run:
```
  Jobs.update({archived:true},{$set:{status:'Archived'}},{multi:true});
```

The results will be this:
```
Document 1
name: "Job1"
archived: true
status: 'Archived'
newField: "Job1"

Document 2
name: "Job2"
archived: true
status: "Archived"
newField: "Job1"
```

Obviously this is a lame example, but its a simpler example than my real use, but the issue is the same, the same modifier is being used for all documents.

Fixing this issue would also help make https://github.com/todda00/meteor-friendly-slugs better which uses this module, which currently is set to look for multi=true and do nothing in that situation.

**Comment by matb33** [comment]
Huh... There is literally nothing I can easily do about it by virtue of how it's a single operation. You get once chance to mutate the modifier, as the underlying call is a single call to mongo too. I don't think we should be changing how update with multi:true behaves as this would mess with how one expects things to go down. What I mean by this is that the only way to make this work as you described is to split a multi:true operation into a find and then looping over the cursor and doing a single update for each match.

Is there a way for you to work around this limitation for your package?

**Comment by matb33** [comment]
Perhaps if you detect multi: true in your before update, do the find loop with individual updates yourself and be sure to return false so the underlying update with multi: true doesn't occur.
