### ISSUE TITLE
.after.update modifier

### ISSUE THREAD

**Issue by mpranjic** [matb33/meteor-collection-hooks#97]
Hi,

I am trying to detect password change with ```Meteor.users.after.update``` and ```modifier``` is undefined, unlike with ```.before.update``` where modifier is correct.

**Comment by matb33** [comment]
Strange... Can you confirm with a small reproduction scenario that I could run?

**Comment by ThaumRystra** [comment]
Just ran into this as well. Can't produce a reproduction though, just one project has undefined modifiers for every after.update hook. The keys exist and are correct, and all the other arguments are defined correctly.

Removing this default option fixed it `CollectionHooks.defaults.all.all = {fetchPrevious: false};`

**Comment by miri-am** [comment]
can confirm. Modifier is always undefined when fetchPrevious is set to false in an after.update hook. Maybe this should be included in documentation?

**Comment by adamwong246** [comment]
+1

**Comment by evolross** [comment]
I just ran into this too. +1

**Comment by matb33** [comment]
Thanks for the `fetchPrevious` hint -- made it much easier to track down and fix. I've deployed the fix in 0.7.14.
