### ISSUE TITLE
Is there any way to make a global hook/callback?

### ISSUE THREAD

**Issue by Lepozepo** [matb33/meteor-collection-hooks#99]
Is there any way to make a global collection hook that runs whenever any collection inserts/updates/removes? Thanks in advance!

**Comment by matb33** [comment]
Unfortunately not... interesting use case though. I can certainly see it being handy if you know for sure you need createdAt/modifiedAt across the board. Is that what you had in mind?

**Comment by Lepozepo** [comment]
My use case is adding a company ID. So basically I have users that belong to a company and anything they create belongs to the company. I currently have collection2 identify the company and add it per collection but I'm repeating that same snippet for every collection schema I make

**Comment by mizzao** [comment]
Not sure if this package would help, but it sounds relevant for you: https://github.com/mizzao/meteor-partitioner

**Comment by Lepozepo** [comment]
That's a pretty interesting solution ^_^
